services:
  db:
    container_name: db
    image: postgres:14
    ports:
      - 5432:5432
    env_file:
      - .env

  goapp:
    container_name: goapp
    image: goapp:1.0.0
    build:
      context: ./server
      dockerfile: go.dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env
